### ISSUE TITLE
in simulate.py - check if inversion has been run first

### ISSUE THREAD

**Issue by danclab** [danclab/laMEG#6]

**Comment by samadpls** [comment]
Hi @jbonaiuto ! Should we add a check to see if the inversion exists in `file['D']['other']` before proceeding with the simulation? If so, I'd like to work on it.

**Comment by jbonaiuto** [comment]
Hi @samadpls, That's right! Though note that ideally it should work with .mat files saved with <v7.3 (see issue #2 ). You can see an example of working with both types of files in util.load_meg_sensor_data
